sudo: false
addons:
  apt:
    packages:
      - libudev-dev

matrix:
  fast_finish: true
  include:
    - python: "3.7.0"
      env: TOXENV=lint
    - python: "3.7.0"
      env: TOXENV=pylint
    - python: "3.7.0"
      env: TOXENV=typing

cache:
  directories:
    - $HOME/.cache/pip
install: pip install -U tox
language: python
script: travis_wait 30 tox --develop
